title: 'Access Rights'
version: "1.0"
released: 2021-02-03
description: 'The Access Rights vocabulary defines concepts to declare the access status of a resource. Multilingual labels regard regional distinctions in language and term.'
namespace: 'http://purl.org/coar/access_right/'
creators:
  - Apollaro, Alberto
  - Aubin, Sophie
  - Azrilevich, Paola
  - Bernal, Isabel
  - Dan, Liu
  - Fripp, Dom
  - Gürdal, Gültekin
  - Habre, Sawsan
  - Hayashi, Yutaka
  - Holt, Ilkay
  - Hua, Nie
  - Jones, Hilary
  - Kataoka, Tomoko
  - Le Borgne, Laurence
  - Liping, Ku (Alan)
  - Mornati, Susanna
  - Ojsteršek, Milan
  - Príncipe, Pedro
  - Schirrwagen, Jochen
  - Shiota,Tomoya
  - Solodovnik, Iryna
  - Steinhoff, Wilko
  - Vedovotto, Nathalie
contributors:
  - COAR Controlled Vocabularies Interest Group