title: 'Resource Types'
version: "3.2"
released: 2024-12-03
description: 'The Resource Type vocabulary defines concepts to identify the genre of a resource. Such resources, like publications, research data, audio and video objects, are typically deposited in institutional and thematic repositories or published in ejournals. This vocabulary supports a hierarchical model that relates narrower and broader concepts. Multilingual labels regard regional distinctions in language and term. Concepts of this vocabulary are mapped with terms and concepts of similar vocabularies and dictionaries.'
namespace: 'http://purl.org/coar/resource_type/'
languages: [ar,ca,cs,da,de,el,en,es,fi,fr,gl,hu,it,ja,ko,nl,pt,ro,ru,sl,sr,sv,sr-cyrl,tr,uk,zh]
creators:
  - name: Isabel Bernal, CSIC, Spain (Editorial Board Chair)
    language:
  - name: Joseph Cera, University of California-Berkeley, US
    language:
  - name: Mick Eadie, University of Glasgow, United Kingdom
    language:
  - name: Benedetta Gandolini, 4Science, Italy
    language:
  - name: Sebastiano Giorgi, UOC, Spain
    language:
  - name: Gültekin Gürdal, Izmir Institute of Technology Library, Turkey
    language:
  - name: Pierre Lasou, Université Laval, Canada
    language:
  - name: Yoo Young Lee, University of Ottawa, Canada
    language:
  - name: Ku (Alan) Liping, Chinese Academy of Science
    language:
  - name: Katharina Menhard, Technische Universität Graz, Austria
    language:
  - name: Gretchen Neidhardt, Northwestern University, United States
    language:
  - name: Milan Ojsteršek, University of Maribor, Slovenia
    language:
  - name: Pedro Príncipe, Universidade do Minho, Portugal
    language:
  - name: Ellen Ramsey, COAR
    language:
  - name: Jochen Schirrwagen, Aachen University, Germany
    language:
  - name: Corinna Schneider, Technische Informationsbibliothek (TIB), Germany
    language:
  - name: Milica Sevkusic, EIFL Serbia
    language:
  - name: Kathleen Shearer, COAR
    language:
contributors:
  - Barbara Aristidou, Cyprus University of Technology, Cyprus
  - Rawia Awadallah, Arab States Research and Education Network
  - Aysen Binen, Izmir Institute of Technology, Turkey
  - Jessica Byström, Chalmers University, Sweden
  - Julie Gauthier, University of Montreal, Canada
  - Diana Furcila Mihalache, FECYT, Spain
  - Hyekyong Hwang, KISTI, Korea
  - Krisztina Korosi, University Library of Corvinus University of Budapest, Hungary
  - Iryna Kuchma, EIFL, Ukraine
  - Christian Lacroix, University of Montreal, Canada
  - Petra Magnusson, Chalmers University, Sweden
  - George Macgregor, University of Glasgow, UK
  - Antonia Nicolaou, Cyprus University of Technology, Cyprus
  - Carmen Posse, University Library of Santiago de Compostela, Spain
  - Irina Razumova, COAR
  - Sa-kwang Song, KISTI, Korea
  - Paul Walk, Antleaf, UK
change_log: |
  - The following new terms were added:
    - archival collection
    - artistic work
    - collection
    - court documents
    - knowledge organization system
    - knowledge synthesis protocol
    - magazine article
    - physical sample
    - research instrument
  - The definition for the term "video" was amended
  - The following language translations were added:
    - Danish
    - Galician
    - Greek
    - Hungarian
    - Korean
    - Romanian
    - Swedish
    - Ukrainian
  - Matches with other controlled vocabularies were also updated for all terms
  
