title: 'Resource Types'
version: "2.0"
released: 2021-02-03
description: 'The Resource Type vocabulary defines concepts to identify the genre of a resource. Such resources, like publications, research data, audio and video objects, are typically deposited in institutional and thematic repositories or published in ejournals. This vocabulary supports a hierarchical model that relates narrower and broader concepts. Multilingual labels regard regional distinctions in language and term. Concepts of this vocabulary are mapped with terms and concepts of similar vocabularies and dictionaries.'
namespace: 'http://purl.org/coar/resource_type/'
creators:
  - Aubin, Sophie
  - Azrilevich, Paola
  - Bernal, Isabel
  - Le Borgne, Laurence
  - Habre, Sawsan
  - Hayashi, Yutaka
  - Holt, Ilkay
  - Hua, Nie
  - Jones, Hilary
  - Kataoka, Tomoko
  - Liping, Ku (Alan)
  - Mornati, Susanna
  - Ojsteršek, Milan
  - Príncipe, Pedro
  - Schirrwagen, Jochen
  - Steinhoff, Wilko
  - Vedovotto, Nathalie
  - Fava, Ilaria (departed)
  - Shiota,Tomoya (departed)
  - Solodovnik, Iryna (departed
  - Subirats, Imma (departed)
  - Wang, Shenghui (departed)
contributors:
  - COAR Controlled Vocabularies Interest Group