title: 'Resource Types'
version: "1.1"
released: 2016-10-01
description: 'The Resource Type vocabulary defines concepts to identify the genre of a resource. Such resources, like publications, research data, audio and video objects, are typically deposited in institutional and thematic repositories or published in ejournals. This vocabulary supports a hierarchical model that relates narrower and broader concepts. Multilingual labels regard regional distinctions in language and term. Concepts of this vocabulary are mapped with terms and concepts of similar vocabularies and dictionaries.'
namespace: 'http://purl.org/coar/resource_type/'
languages: [en]
creators:
  - name: Gültekin Gürdal
    language: Turkish
  - name: Hilary Jones
    language: English
  - name: Ilaria Fava
    language: Italian
  - name: Ilkay Holt
    language: Turkish
  - name: Imma Subirats
    language: Catalan
  - name: Iryna Solodovnik
    language: Russian
  - name: Isabel Bernal
    language: Spanish
  - name: Jochen Schirrwagen
    language: German
  - name: Paola Azrilevich
    language: Spanish
  - name: Pedro Príncipe
    language: Portuguese
  - name: Sandor Kopacsi
    language: Czech
  - name: Shenghui Wang
    language: Chinese
  - name: Sophie Aubin
    language: French
  - name: Wilko Steinhoff
    language: Dutch
contributors:
  - COAR Controlled Vocabularies Interest Group