title: 'Version Types'
version: "1.0_draft"
released: 2018-07-01
description: 'The Version Type vocabulary defines concepts to declare the version of a resource. Multilingual labels regard regional distinctions in language and term. The concepts are adopted from the \"Journal Article Versions (JAV): Recommendations of the NISO/ALPSP JAV Technical Working Group\", https://www.niso.org/publications/niso-rp-8-2008-jav'
namespace: 'http://purl.org/coar/version/'
creators:
  - name: Alberto Apollaro
    language:
  - name: Sophie Aubin
    language: French
  - name: Paola Azrilevich
    language:
  - name: Isabel Bernal
    language: Spanish
  - name: Dan Liu
    language:
  - name: Ilaria Fava
    language:
  - name: Dom Fripp
    language: English
  - name: Gültekin Gürdal
    language: Turkish
  - name: Sawsan Habre
    language:
  - name: Ilkay Holt
    language: Turkish
  - name: Nie Hua
    language:
  - name: Hilary Jones
    language: English
  - name: Tomoko Kataoka
    language: Japanese
  - name: Laurence Le Borgne
    language: Japanese
  - name: Ku (Alan) Liping
    language: Chinese
  - name: Pedro Príncipe
    language: Portugeuse
  - name: Jochen Schirrwagen
    language: German
  - name: Tomoya Shiota
    language: Japanese
  - name: Iryna Solodovnik
    language:
  - name: Wilko Steinhoff
    language: Dutch
  - name: Nathalie Vedovotto
    language:
contributors:
  - COAR Controlled Vocabularies Interest Group